# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
meta_h: True
meta_h_interval: 1000

runner: "meta"
batch_size_run: 8

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "hierarchical_q_learner"
double_q: True
mixer: "hqmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

# for latent model
name: "qmix_smac_hierarchical_meta"

agent: "hierarchical_rnn"
mac: "hierarchical_mac"

latent_dim: 3
kl_loss_weight: 0.0001
h_loss_weight: 0.0001
var_floor: 0.002
NN_HIDDEN_SIZE: 16
dis_loss_weight: 0.001
dis_time: 0
soft_constraint_weight: 1.0
roma_raw: False
meta_lr: 0.00005
use_step_reward: True
concat_ori_s: True
hie_grad_qtot: True
use_roma: False
random_agent_order: False

dis_sigmoid: False


use_tensorboard: True
save_model: True
use_cuda: True
device_num: 0
save_replay: False
